### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Im-Kayun** [renzuzu/renzu_shops#1]
One improvement that would be interesting, is that the stores could be whitelisted. For example, a police armory that uses this store system, but only officers can open and buy.

**Comment by renzuzu** [comment]
for defaults shops like police armoury, ambulance supply which are not included in ownedshops config are already possible.
by putting
```
groups = 'police',
```
```
PoliceArmoury = {
		moneytype = 'money',
		name = 'Police Armoury',
		groups = 'police',
		blip = {
			id = 110, colour = 84, scale = 0.8
		}, inventory = {
			{ name = 'ammo-9', price = 5, },
			{ name = 'ammo-rifle', price = 5, },
			{ name = 'WEAPON_FLASHLIGHT', price = 200 },
			{ name = 'WEAPON_NIGHTSTICK', price = 100 },
			{ name = 'WEAPON_PISTOL', price = 500, metadata = { registered = true, serial = 'POL' }, license = 'weapon' },
			{ name = 'WEAPON_CARBINERIFLE', price = 1000, metadata = { registered = true, serial = 'POL' }, license = 'weapon', grade = 3 },
			{ name = 'WEAPON_STUNGUN', price = 500, metadata = { registered = true, serial = 'POL'} }
		}, locations = {
			vec3(451.51, -979.44, 30.68)
		}
	},
	```
	
	as for the ownedshops config/ownedshops/*.lua
	its implemented
	
	https://github.com/renzuzu/renzu_shops/commit/75baee6eaf935ae8e4a0a3f92d7b50fee38657dd
	
	registering the job/group owneds shops is the same with default shop logic

**Comment by renzuzu** [comment]
unfortunately its the feature of shop.

you can add multiple metadatas on each item from cart even if its the same item. (item customise when you click the burger picture)
thats why its needed to be like this as for now.

**Comment by Im-Kayun** [comment]
When you go to buy an item in the store and click on it, the customization menu only appears if the item has several options. 
Ex: burger

**Comment by Im-Kayun** [comment]
The Support Multiple Frameworks (easy) task is marked as done, but I suppose it is at an early stage, correct?
Because I am testing in QB and there are still a lot of database related errors

**Comment by renzuzu** [comment]
> When you go to buy an item in the store and click on it, the customization menu only appears if the item has several options.
> Ex: burger

i think we can exclude the item from non merging cart if the item was no metadatas extras from customisation.

>The Support Multiple Frameworks (easy) task is marked as done, but I suppose it is at an early stage, correct?
Because I am testing in QB and there are still a lot of database related errors

and this , i honestly i havent tested properly.
since the only used here in the resource was the getplayerfrom id from ESX

if you say Database its related to vehicleshop? thats the only part of script haves database connection and the taco van movable shops.

can you show the throwing error from database? it could be missing default fields i assume.

**Comment by Im-Kayun** [comment]
The errors that do exist are related to tables and fields. In the case of the table, the script uses owned_vehicles, but in qb it is player_vehicles. In the fields, the script tries to insert data into fields that qb does not use.

**Comment by Im-Kayun** [comment]
When you put a product in the cart, you can put a quantity of 0 or negative.

**Comment by Im-Kayun** [comment]
Hi renzu, I am testing the script and I think the script has strong points but some very confusing parts and some bugs. It has been talked about before but I think the suggestion was not clarified well. The store owner would have the possibility to create new categories and could add new items that he has with him in the inventory and not only the ones in the store config. For example, I could create a new category and put a repair kit that I have in my inventory for sale and not only the items that are in the store config. I also tested creating a new category and restarting the server but the category did not save... is it my problem because I am using ox_inventory and not the fork you created? Wouldn't it be better to store all the information regarding the stores in one or several database tables? It would be easier to visualize and organize in my opinion. To finalize, I deleted a folder called db that is next to the cache folder and the store owners were deleted, hence my suggestion to save in the database.

Thanks and sorry for such a long text.

**Comment by renzuzu** [comment]
sorry i been busy. i havent reply fast.

>create new categories and could add new items that he has with him in the inventory and not only the ones in the store config

this is possible but adding item from inventory is like a chaos for a RP server.
owner can start selling ex. drug item
but with blacklisting feature it will be good.

the blacklisting config will be per Shop type.
so in general store you cant sell weapons for example.

> I also tested creating a new category and restarting the server but the category did not save..

category are temporary until you create a new item for it. thats how i made it.

> Wouldn't it be better to store all the information regarding the stores in one or several database tables?

in my other resource i always experience different issue and most of them are database issue. like old mysql version. or others.

so far now no one complaining in KVP logic.

but i will think about it, since i only support ox_sql. oxsql does not support older mysql version.
