### ISSUE TITLE
can't use target after updating

### ISSUE THREAD

**Issue by Sampuke** [renzuzu/renzu_shops#15]

**Comment by renzuzu** [comment]
any more info?
my ox_target still work on the resource

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_shops/commit/ce32ea498d58c78ec7ad1bb2db73d7cc910ee6b2
fix
Thanks

**Comment by Sampuke** [comment]
I don't really know I update the recourse yesterday and now I can't turn on using ox_target / target

Also could you use releases so if this happens I could just download the older version

**Comment by Sampuke** [comment]
Also when I take the taco truck it works but when I use either the hotdog or burger stand the ox lib menu stays on my screen and I can't use the cart

**Comment by renzuzu** [comment]
there is a bug in state bag now , its currently fixed in latest build of client 
i have a fix on my local. but i have to finish something first.

the ox_target works fine with me

can you do a step by step problem before and after the  problem
else i cant reproduce the bug since it works fine with me

**Comment by Sampuke** [comment]
so i just saw that you had updated something and i decided to update. then i downloaded from github and changed a few things in configs

**Comment by Sampuke** [comment]
Now when i updated it works.
