### ISSUE TITLE
renzu shop issue

### ISSUE THREAD

**Issue by IT21179594** [renzuzu/renzu_shops#33]
i used your shops script it would be great but i have one questions when i open the shop the ox inventory shops is also open how can i remove ox inventory shop and this green blip

**Comment by renzuzu** [comment]
i revert my changes last week
https://github.com/renzuzu/renzu_shops/commit/a25e2fd58bdfa258b0c2d02590e0a6af91f111d3

the cost the red notifcation from ox inventory will re appear.. instead of this conflict issue in both shop..


to solve this problem you need to disable the ox shop completely by removing the shop it self and every coordinates.

or use my ox_inventory forked version . my forked updates the client and green marker will be removed too
