### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by KuroScripts** [renzuzu/renzu_shops#8]
a npc employee that you can hire that sells to customers with animations and reminds the owner when there no more stock and after a certain amount of time it takes the money from the cashier into the vault and even a robbing likes these and if the npc dies the store closes for a certain amount of time

https://www.youtube.com/watch?v=l926BP_HdS8
https://streamable.com/g31y4

**Comment by KuroScripts** [comment]
I Can send you the releases of the videos I sent

**Comment by renzuzu** [comment]
i will implement a option that you can hire people.
what the local npc will do?
only stand?
im thinking that the local can sell to locals too :D

the idea of local will move the money to vault is not good.

because its a vault . only owner should have access on it.
and also the shop robbery will be useless

because the money of cashier is the one getting robbed

the idea of when npc dies, the shop going to closed for a while is good
